layers: 24
heads: 24
query_groups: 4
intermediate_dim: 8192
embedding_dim: 1600
# We follow the GPT-2 architecture to decide the above parameters.
# https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/configuration_gpt2.py?t