natural_language_understanding:
  name: natural_language_understanding
  dataset_names:
    - glue_cola
    - glue_sst2
    - glue_mrpc
    - glue_mnli_matched
    - glue_mnli_mismatched
    - glue_qnli
    - glue_rte
    - glue_wnli
    - glue_qqp
    # - stsb
    - superglue_boolq
    - superglue_cb
    - superglue_copa
    - superglue_multirc
    - superglue_record
    - superglue_rte
    - superglue_wic
    - superglue_wsc