natural_language_understanding:
  name: natural_language_understanding
  dataset_names:
    - cola
    - sst2
    - mrpc
    - mnli_matched
    - mnli_mismatched
    - qnli
    - rte
    - wnli
    - qqp
    # - stsb