# Optimization parameters
precision: 16-mixed
gradient_accumulation_steps: 10
per_device_batch_size: 2
max_epochs: 1

# Logging and checkpointing
logging_steps: 500
checkpoint_save_steps: null
resume_ckpt_path: null
checkpoint_save_interval_hours: 6

# Dataloader
num_workers: 8
train_dataset_name: pints_ai
