# Optimization parameters
precision: 16-mixed
gradient_accumulation_steps: 10
per_device_batch_size: 2
max_epochs: 1

# Logging and checkpointing
logging_steps: 500
checkpoint_save_steps: 10000
resume_ckpt_path: Null

# Dataloader
num_workers: 8
train_dataset_name: pints_ai
