# Optimization parameters
precision: 16-mixed
gradient_accumulation_steps: 15
per_device_batch_size: 18
max_epochs: 1

# Logging and checkpointing
logging_steps: 100
checkpoint_save_steps: 10000
resume_ckpt_path: Null

# Dataloader
num_workers: 8
