_global:
    seed: 10
    tag: "default"
    root_dir: "/root/RETRO/runs"
    eval_dir: "/root/RETRO/eval"
    is_debug: False
defaults:
    - _self_
    - model: default
    - dataset: default
    - training: default