_global:
    seed: 10
    tag: "default"
    root_dir_path: "/root/RETRO/"
    log_dir: "runs"
    is_debug: False
defaults:
    - _self_
    - model: rellama
    - dataset: default
    - training: default
    - eval: null
    - optimizer: adafactor

hydra:
  output_subdir: null
  run:
    dir: ./runs/