_global:
    seed: 10
    tag: "default"
    root_dir_path: "/root/RETRO/"
    log_dir: "runs"
    is_debug: False
defaults:
    - _self_
    - model: rellama
    - dataset: pints_ai
    - eval: null
    - optimizer: adamw
    - lr_scheduler: linear_decay
    - training: default
    - testing: default
hydra:
  output_subdir: null
  run:
    dir: ./runs/