# Global configs
use_torch_compile: True
seed: 10
tag: "default"
root_dir_path: "/root/RETRO/"
log_dir: "runs"
is_debug: False

# Defaults
defaults:
    - _self_
    - model: rellama
    - dataset:
        - pints_ai
        - lambada
        - wikitext
        - curation
    - task:
        - last_word_prediction
        - next_token_prediction
    - optimizer: adamw
    - lr_scheduler: linear_decay
    - training: default
    - validation: default
    - testing: default
hydra:
  output_subdir: null
  run:
    dir: ./runs/