# Global configs
use_torch_compile: True
seed: 10
tag: "default"
root_dir_path: "/root/RETRO/"
log_dir: "runs"
is_debug: False
notify_start: False
notify_end: True

# Defaults
defaults:
    - _self_
    - model: llama
    - dataset:
        - pints_ai
        - lambada
        - wikitext
        - curation
        - cola
        - sst2
        - mrpc
    - task:
        - last_word_prediction
        - next_token_prediction
        - natural_language_understanding
    - optimizer: adamw
    - lr_scheduler: linear_decay
    - training: default
    - validation: default
    - testing: default
hydra:
  output_subdir: null
  run:
    dir: ./runs/