val_dataset_name: lambada
per_device_batch_size: 10
val_check_interval: 0.5
check_val_every_n_epoch: 1
num_sanity_val_steps: 2
num_workers: 8

task_names:
  - last_word_prediction
  - next_token_prediction