# Retrieval configs
use_gpu: True
return_as_str: False
topk: 10

# For connection to the retrieval server
address: "http://localhost"
port: 7000

# For saving the encoded vector embeddings
embedding_dir_path: "data/retrieval/embeddings"
retrieved_chunk_ids_dir_path: "data/retrieval/chunk_ids"
shard_size: 100_000_000
meta_file_name: "meta.json"

# For encoding
encoding:
  model_name: joe32140/ModernBERT-large-msmarco
  batch_size: 1
  num_total_workers: 37
  worker_start_idx_of_current_server: 0
  num_workers_in_current_server: 2
  num_dataloader_workers: 8
  passage_size: 1024
  chunk_size: 64

# For indexing
indexing:
  index_path: "data/retrieval/indexes/faiss_ivfpq.index"
  num_subquantizers: 32
  bits_per_subvector: 8
  train_size: 10_000_000
  batch_size: 5_000
  dim: 1024

# For retrieving
retrieving:
  num_total_workers: 39
  worker_start_idx_of_current_server: 0
  num_workers_in_current_server: 2
  num_dataloader_workers: 8
  batch_size: 100
