# Retrieval configs
use_gpu: True
return_as_str: False
topk: 10

# For connection to the retrieval server
address: "http://localhost"
port: 7000
dir_path: "data/retrieval"
corpus_name: "pile"


defaults:
  - _self_
  - model: sparse

