xs:
  layers: 6
  num_attention_heads: 6
  num_key_value_heads: 2 # this should be factor of num_attention_heads
  intermediate_size: 1536
  hidden_size: 384
  # We follow the GPT-2 architecture to decide the above parameters.
  # https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/configuration_gpt2.py?t