glue_qqp:
  name: glue_qqp
  huggingface_dataset_name: nyu-mll/glue
  subset: qqp
  split_mapping:
    train: train
    validation: validation
    test: validation
  dir_name: data
  remove_columns: ["label", "question1", "question2"]