glue_sst2:
  name: glue_sst2
  huggingface_dataset_name: nyu-mll/glue
  subset: sst2
  split_mapping:
    train: train
    validation: validation
    test: validation
  dir_name: data
  remove_columns: ["label", "sentence"]