glue_cola:
  name: glue_cola
  huggingface_dataset_name: nyu-mll/glue
  subset: glue_cola
  split_mapping:
    train: train
    validation: validation
    test: validation
  dir_name: data
  remove_columns: ["label", "sentence"]