pints_ai:
  name: pints_ai
  huggingface_dataset_name: pints-ai/Expository-Prose-V1
  subset: null
  split_mapping:
    train: train
    validation: null
    test: null
  dir_name: data
  remove_columns:
    - text
    - source_id
    - source