wikitext:
  name: wikitext
  huggingface_dataset_name: Salesforce/wikitext
  subset: wikitext-103-v1
  split_mapping:
    train: null
    validation: test
    test: test
  dir_name: data
  remove_columns: []